### ISSUE TITLE
add cjs dist build output?

### ISSUE THREAD

**Issue by subtleGradient** [slevithan/regex#16]
for horrifically annoying and stupid reasons beyond my ability/interest to control, I am forced to keep using CommonJS in 2024. Only way I could use this was by manually copying the min.js file into our code and exporting it myself.

it'd be hip if there was a cjs CommonJS file in the distribution so this Just Works™

also, SO thrilled I'm finally getting to use your stuff!
I've been a huge fan for like 372 years

**Comment by slevithan** [comment]
Thanks, @subtleGradient! 😊🙌

I'm totes open to adding a CJS build/export, but to be totes honest I'm not very knowledge about CJS or providing dual ESM/CJS exports. Would you be open to submitting a PR for this?

**Comment by subtleGradient** [comment]
sure! I can give it a shot

**Comment by subtleGradient** [comment]
CommonJS bundle and sourcemaps #18
