### ISSUE TITLE
Feat: Add types

### ISSUE THREAD

**Issue by slevithan** [slevithan/regex#4]
I would be happy to add types to `regex`, along with its extension [`regex-recursion`](https://github.com/slevithan/regex-recursion) and their shared utilities [`regex-utilities`](https://github.com/slevithan/regex-utilities).

I'd love help with this or for someone to take over this issue. The types are fairly complex and I'm not yet well-versed with TypeScript.

**Comment by rauschma** [comment]
* I have never written `.d.ts` files manually, but this should work: https://github.com/rauschma/regex-types
* It should be enough to move `index.d.ts` next to `index.js` (no need to change `package.json`).
* Tool for checking if everything worked out: https://github.com/arethetypeswrong/arethetypeswrong.github.io

**Comment by slevithan** [comment]
Amazing--thank you!!

Can I interest you in submitting this as a PR? 😊 I'd love for your work to be officially credited in the contributors list. If not, I'll come back to this later and figure it out. Thanks either way

PS: I'm a *longtime* fan of your JS and regex work/writing. I'd welcome the opportunity to add you as a collaborator if at any point you're interested in being more involved.

**Comment by rauschma** [comment]
> Can I interest you in submitting this as a PR?

I just did.

> I'm a _longtime_ fan of your JS and regex work/writing.

Cool! I’ve also been a fan of your work for a long time. Proof 😀 (written in 2014): https://exploringjs.com/es5/ch30.html#_four_language_libraries

> I'd love to add you as a collaborator for the repo if at any point you're interested in being more involved.

I have too many other projects that I’m working on at the moment, but I’ll keep it in mind.
