### ISSUE TITLE
Rename `partial` → `pattern`

### ISSUE THREAD

**Issue by slevithan** [slevithan/regex#7]
I'm considering renaming function/tag `partial` as `pattern`, and class `PartialPattern` as `Pattern`. The latter isn't directly usable, but return values of `partial` are instances of this class. These changes would be included in v3.0.0.

@rauschma, since you wrote about `regex` and `partial` [here](https://exploringjs.com/js/book/ch_template-literals.html#regex-library), I wanted to give you a heads up about this. Do you think this is a good idea?

**Comment by rauschma** [comment]
I like it! The new name feels more intuitive to me.

**Comment by slevithan** [comment]
This is now published in [v3.0.0](https://github.com/slevithan/regex/releases/tag/v3.0.0). 😊 Hopefully it's easy to update in [*Exploring JavaScript*](https://exploringjs.com/js/book/ch_template-literals.html#regex-library).

**Comment by rauschma** [comment]
I already made the change – it’ll be in the next release. 😀
